version: "3.7"
services:
    express-jwt-redis:
        container_name: express-jwt-redis
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "2999:2999"
        volumes:
            - ./:/usr/local/app/
            - /usr/local/app/node_modules/
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        networks:
            - backend
        environment:
            TZ: "Asia/Bangkok"

networks:
    backend:
        external:
            name: backend
