name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Define env file
              uses: SpicyPizza/create-envfile@v1
              with:
                  PORT: 2999
                  SECRET_TOKEN: SECRET_JWT_BRA
                  file_name: .env
            - name: Build Express and Restart Container
              run: docker-compose up -d && docker restart express-jwt-redis
