name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Define env file
              run: |
                  touch .env
                  echo SECRET_TOKEN=SECRET_JWT_BRA >> .env
                  echo PORT=2999 >> .env
                  cat .env
            - name: Build Express and Restart Container
              run: docker-compose up -d && docker restart express-jwt-redis
