name: Docker Image CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    store_static:
        runs-on: self-hosted
        steps:
            - uses: actions/upload-artifact@v2
              with:
                  name: store_json_data
                  path: data/
    build:
        runs-on: self-hosted
        needs: store_static
        steps:
            - uses: actions/checkout@v2
            - name: Download Static
              uses: actions/download-artifact@v2
              with:
                  name: store_json_data
                  path: data/
            - name: Define env file
              run: |
                  touch .env
                  echo SECRET_TOKEN=SECRET_JWT_BRA >> .env
                  echo PORT=2999 >> .env
                  cat .env
            - name: Build Express and Restart Container
              run: docker-compose up -d && docker restart express-jwt-redis
